spring:
  application:
    name: micromarket
  datasource:
    url: jdbc:mysql://junction.proxy.rlwy.net:53113/railway
    username: root
    password: IVYzgzySSkTLjmggoZhHfUCjeDaZJsZI
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties: 
      hibernate: 
        '[format_sql]': true
        dialect: org.hibernate.dialect.MySQLDialect
      database-platform: org.hibernate.dialect.MySQLDialect

jackson:
  serialization:
    indent-output: true

logging:
  level:
    '[org.springframework]': INFO
    '[org.hibernate.sql]': DEBUG
    '[org.hibernate.type.descriptor.sql]': TRACE

server:
  port: 9090
  servlet: 
    context-path: /micromarket

security:
  jwt:
    # Genera llave secreta con openssl rand -base64 32
    secret-key: efmycl3ZY1LasnSGalvccYA1nR5Yo3r9WdWYoHft8rY=
    token-expiration: 600000 # 10 min expresado en ms